# Generated by Django 3.1.5 on 2021-01-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('conference', models.CharField(max_length=256)),
                ('abbreviation', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('games_played', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('win_percentage', models.FloatField()),
                ('rating', models.FloatField()),
                ('strength_of_schedule', models.FloatField()),
                ('conference_wins', models.IntegerField()),
                ('conference_losses', models.IntegerField()),
                ('home_wins', models.IntegerField()),
                ('home_losses', models.IntegerField()),
                ('away_wins', models.IntegerField()),
                ('away_losses', models.IntegerField()),
            ],
        ),
    ]
