# Generated by Django 3.1.5 on 2021-01-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCAAB', '0002_auto_20210112_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='win_percentage',
            field=models.FloatField(null=True),
        ),
    ]
