# Generated by Django 3.1.5 on 2021-01-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCAAB', '0002_auto_20210114_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='conference_losses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='conference_wins',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='home_wins',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='losses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='wins',
            field=models.IntegerField(null=True),
        ),
    ]
