# Generated by Django 3.1.5 on 2021-01-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCAAB', '0003_auto_20210112_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='strength_of_schedule',
            field=models.FloatField(null=True),
        ),
    ]
