# Generated by Django 3.1.5 on 2021-01-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCAAB', '0004_auto_20210112_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='away_losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='away_wins',
        ),
        migrations.RemoveField(
            model_name='team',
            name='conference_losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='conference_wins',
        ),
        migrations.RemoveField(
            model_name='team',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='team',
            name='home_losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='home_wins',
        ),
        migrations.RemoveField(
            model_name='team',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='team',
            name='strength_of_schedule',
        ),
        migrations.RemoveField(
            model_name='team',
            name='win_percentage',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wins',
        ),
    ]
