# Generated by Django 3.1.5 on 2021-01-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCAAB', '0005_auto_20210118_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameboxscore',
            name='away_steal_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gameboxscore',
            name='away_steals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gameboxscore',
            name='away_three_point_field_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gameboxscore',
            name='away_total_rebound_percentage',
            field=models.FloatField(null=True),
        ),
    ]
