# Generated by Django 3.1.5 on 2021-01-19 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCAAB', '0007_auto_20210118_2312'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameboxscore',
            unique_together={('date', 'loser')},
        ),
        migrations.RemoveField(
            model_name='gameboxscore',
            name='winner',
        ),
    ]
