# Generated by Django 3.1.5 on 2021-01-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCAAB', '0009_auto_20210118_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerboxscore',
            name='player',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
