# Generated by Django 3.1.5 on 2021-01-19 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCAAB', '0010_auto_20210118_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerboxscore',
            old_name='field_goals_attempted',
            new_name='field_goal_attempts',
        ),
        migrations.RenameField(
            model_name='playerboxscore',
            old_name='field_goals_made',
            new_name='field_goals',
        ),
        migrations.RenameField(
            model_name='playerboxscore',
            old_name='free_throws_attempted',
            new_name='free_throw_attempts',
        ),
        migrations.RenameField(
            model_name='playerboxscore',
            old_name='free_throws_made',
            new_name='free_throws',
        ),
        migrations.RenameField(
            model_name='playerboxscore',
            old_name='three_pointers_attempted',
            new_name='three_point_attempts',
        ),
        migrations.RenameField(
            model_name='playerboxscore',
            old_name='three_pointers_made',
            new_name='three_pointers',
        ),
        migrations.RenameField(
            model_name='playerboxscore',
            old_name='two_pointers_attempted',
            new_name='two_point_attempts',
        ),
        migrations.RenameField(
            model_name='playerboxscore',
            old_name='two_pointers_made',
            new_name='two_pointers',
        ),
    ]
