# Generated by Django 3.1.5 on 2021-01-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCAAB', '0011_auto_20210118_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameboxscore',
            name='location',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
