# Generated by Django 3.1.5 on 2021-01-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCAAB', '0013_tweet_twitteraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteraccount',
            name='id',
        ),
        migrations.AddField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='favorite_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='in_reply_to_screen_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='in_reply_to_status_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='in_reply_to_user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='quoted_status_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='handle',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
