# Generated by Django 3.1.5 on 2021-01-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCAAB', '0016_auto_20210120_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='in_reply_to_status_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='in_reply_to_user_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='quoted_status_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
