# Generated by Django 3.1.5 on 2021-01-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCAAB', '0017_auto_20210120_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='quoted_status_id',
        ),
    ]
