# Generated by Django 3.1.5 on 2021-01-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCAAB', '0018_remove_tweet_quoted_status_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='account',
        ),
        migrations.DeleteModel(
            name='TwitterAccount',
        ),
    ]
