# Generated by Django 3.1.5 on 2021-01-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCAAB', '0019_auto_20210120_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
