# Generated by Django 3.1.5 on 2021-01-20 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NCAAB', '0020_delete_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('created_at', models.DateTimeField(null=True)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('full_text', models.CharField(max_length=1000, null=True)),
                ('in_reply_to_status_id', models.CharField(max_length=255, null=True)),
                ('in_reply_to_user_id', models.CharField(max_length=255, null=True)),
                ('in_reply_to_screen_name', models.CharField(max_length=255, null=True)),
                ('retweet_count', models.IntegerField(null=True)),
                ('favorite_count', models.IntegerField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NCAAB.twitteraccount')),
            ],
        ),
    ]
